apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acquisitions-app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - acquisitions.example.com
      secretName: acquisitions-tls
  rules:
    - host: acquisitions.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: acquisitions-app
                port:
                  number: 80
