# Base Ingress example (disabled by default in base)
# - Overlays can include with the appropriate host and TLS settings
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acquisitions-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: acquisitions.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: acquisitions-app
                port:
                  number: 80
